# wrangler.toml

name = "wg-workers"
main = "functions/submit-form.js" # Entry point to your Worker script

account_id = "af6be66b546b6c94de43eba8358b3fa2" # Replace with your actual account ID
workers_dev = false
route = "https://wallacegraham.com/api/submit-form"
compatibility_date = "2024-10-02"

[env.production]
name = "wg-workers-production"
main = "functions/submit-form.js" # Ensure consistency across environments
route = "https://wallacegraham.com/api/submit-form" # Replace with your actual domain and path
compatibility_date = "2024-10-02"

